src/Entity/ReviewAssignment.php
<?php

namespace App\Entity;

use App\Repository\ReviewAssignmentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;  

/**
 * @ORM\Entity(repositoryClass=ReviewAssignmentRepository::class)
 */
class ReviewAssignment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Submission::class, inversedBy="submission_reviewAssignments")
     */
    private $submission;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="rewiewer_reviewAssignments")
     */
    private $reviewer; 
    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $duedate;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $invitation_sent_at;
    // ^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@\ju.edu.et

    /**
     * @ORM\Column(type="string", length=255, nullable=true)     
     */
    private $external_reviewer_email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $external_reviewer_name;

     /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $middle_name;


     /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $last_name;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Declined;




    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $reassigned;



    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $file_tobe_reviewed;


    /**
     * @ORM\Column(type="date")
     */
    private $invitationDueDate;

    /**
     * @ORM\Column(type="integer")
     */
    private $status;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $acceptedAt;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $rejectedAt;

    /**
     * @ORM\OneToMany(targetEntity=Review::class, mappedBy="reviewAssignment", orphanRemoval=true)
     */
    private $reviews;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $closed;
    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $reviewfile;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $inactive_assignment;

    public function __construct()
    {
        $this->reviews = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSubmission(): ?Submission
    {
        return $this->submission;
    }

    public function setSubmission(?Submission $submission): self
    {
        $this->submission = $submission;

        return $this;
    }

    public function getReviewer() 
    {
        return $this->reviewer;
    }

    public function setReviewer(?User $reviewer): self
    {
        $this->reviewer = $reviewer;

        return $this;
    }

    public function getDuedate(): ?\DateTimeInterface
    {
        return $this->duedate;
    }

    public function setDuedate(?\DateTimeInterface $duedate): self
    {
        $this->duedate = $duedate;

        return $this;
    }

    public function getInvitationSentAt(): ?\DateTimeInterface
    {
        return $this->invitation_sent_at;
    }

    public function setInvitationSentAt(?\DateTimeInterface $invitation_sent_at): self
    {
        $this->invitation_sent_at = $invitation_sent_at;

        return $this;
    }
    
    public function getDeclined(): ?string
    {
        return $this->Declined;
    }
    public function setDeclined(?string $Declined): self
    {
        $this->Declined = $Declined;

        return $this;
    }


    public function getReassigned(): ?string
    {
        return $this->reassigned;
    }
    public function setReassigned(?string $reassigned): self
    {
        $this->reassigned = $reassigned;

        return $this;
    }


    
    public function getFileTobeReviewedeclined(): ?string
    {
        return $this->file_tobe_reviewed;
    }
    public function setFileTobeReviewed(?string $file_tobe_reviewed): self
    {
        $this->file_tobe_reviewed = $file_tobe_reviewed;

        return $this;
    }

    

    public function getExternalrevieweremail(): ?string
    {
        return $this->external_reviewer_email;
    }
    public function setExternalrevieweremail(?string $external_reviewer_email): self
    {
        $this->external_reviewer_email = $external_reviewer_email;

        return $this;
    }

 
    
    public function getExternalreviewerName(): ?string
    {
        return $this->external_reviewer_name;
    }
    
    public function setExternalreviewerName(?string $external_reviewer_name): self
    {
        $this->external_reviewer_name = $external_reviewer_name;

        return $this;
    }

    
    
    public function getMiddleName(): ?string
    {
        return $this->middle_name;
    }
    
    public function setMiddleName(?string $middle_name): self
    {
        $this->middle_name = $middle_name;

        return $this;
    }
    


    
    public function getLastName(): ?string
    {
        return $this->last_name;
    }
    
    public function setLastName(?string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }
    

    public function getInvitationDueDate(): ?\DateTimeInterface
    {
        return $this->invitationDueDate;
    }

    public function setInvitationDueDate(\DateTimeInterface $invitationDueDate): self
    {
        $this->invitationDueDate = $invitationDueDate;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getAcceptedAt(): ?\DateTimeInterface
    {
        return $this->acceptedAt;
    }

    public function setAcceptedAt(?\DateTimeInterface $acceptedAt): self
    {
        $this->acceptedAt = $acceptedAt;

        return $this;
    }

    public function getRejectedAt(): ?\DateTimeInterface
    {
        return $this->rejectedAt;
    }

    public function setRejectedAt(?\DateTimeInterface $rejectedAt): self
    {
        $this->rejectedAt = $rejectedAt;

        return $this;
    }
    public function getIsAccepted()
    {
        return $this->acceptedAt != null;
    }
    public function getIsRejected()
    {
        return $this->rejectedAt != null;
    }

    /**
     * @return Collection|Review[]
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setReviewAssignment($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getReviewAssignment() === $this) {
                $review->setReviewAssignment(null);
            }
        }

        return $this;
    }

    public function getClosed(): ?bool
    {
        return $this->closed;
    }

    public function setClosed(?bool $closed): self
    {
        $this->closed = $closed;

        return $this;
    }
    public function getReviewfile(): ?bool
    {
        return $this->reviewfile;
    }

    public function setReviewfile(?bool $reviewfile): self
    {
        $this->reviewfile = $reviewfile;

        return $this;
    }

    public function getInactiveAssignment(): ?bool
    {
        return $this->inactive_assignment;
    }

    public function setInactiveAssignment(?bool $inactive_assignment): self
    {
        $this->inactive_assignment = $inactive_assignment;

        return $this;
    }
    
}

src/Form/ReviewAssignmentType.php
<?php

namespace App\Form;

use App\Entity\ReviewAssignment;
use App\Entity\User;
use DateTime;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class ReviewAssignmentType extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options) {
        $reviewAssignment = $options['data'];
        if (!$reviewAssignment instanceof ReviewAssignment) {
            return;
        }
        $builder
            // ->add('reviewer', EntityType::class, array(
            //     'placeholder' => '---Select reviewer   ---',

            //     'class' => 'App\Entity\User',
            //     'attr' => array(
            //         // 'empty' => 'Reviewers from System',
            //         'required' => true,
            //         'class' => 'select2   ',
            //     ),
            // ))
            ->add('reviewer', EntityType::class, [
                 'placeholder' => '---Select reviewer   ---',

                "class" =>  'App\Entity\User',
                 
            ])

            ->add('reviewfile',  ChoiceType::class, [
                'choices' => [
                 'Original' => 0,
                 'New File' => 1,
                 ],
                 'label'=>'File to be reviewed',
                'expanded'=>true,
                'attr' => [
                        'class' => 'form-horizontal  ',
                      'required' => true,
                    'multiple'=>false,
                'onclick' => 'attachOrDoi();',

                       ] ,            
                    ]) 
            ->add('file_tobe_reviewed', FileType::class, [
                'label' => 'Upload proposal attachment',
                'mapped' => false, 'attr' => [
                    'class' => 'form-control  m-0   ',
                    'required' => true,

                ],
                'required' => true,
            ])

            ->add('invitationDueDate', DateType::class, array(
                'placeholder' => [
                    'year' => 'Year', 'month' => 'Month', 'day' => 'Day'],
                'label' => 'Invitation response duedate',

                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
                'attr' => array(
                    'min' => (new DateTime('now'))->format('Y-m-d'),
                    'max' => $reviewAssignment->getSubmission()->getCallForProposal()->getReviewProcessEnd()->format('Y-m-d'),

                    'required' => true,
                    'class' => 'form-control',
                ),
            ))
            ->add('duedate', DateType::class, array(
                'placeholder' => [
                    'year' => 'Year', 'month' => 'Month', 'day' => 'Day'],
                'label' => 'Review duedate',
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
                'attr' => array(
                    'min' => (new DateTime('now'))->format('Y-m-d'),
                    'max' => $reviewAssignment->getSubmission()->getCallForProposal()->getReviewProcessEnd()->format('Y-m-d'),
                    'required' => true,
                    'class' => 'form-control',
                ),
            ))

        ;
    }

    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults([
            'data_class' => ReviewAssignment::class,
        ]);
    }
}

class ExternalReviewAssignmentType extends AbstractType {
    public function buildForm(FormBuilderInterface $builder, array $options) {
        $reviewAssignment = $options['data'];
        if (!$reviewAssignment instanceof ReviewAssignment) {
            return;
        }
        $builder

            ->add('external_reviewer_name')
            ->add('middle_name')
            ->add('last_name')

            ->add('reviewfile',  ChoiceType::class, [
                'choices' => [
                 'Original' => 0,
                 'New File' => 1,
                 ],
                 'label'=>'File to be reviewed',
                'expanded'=>true,
                'attr' => [
                        'class' => 'form-group  ',
                      'required' => true,
                    'multiple'=>false,
                'onclick' => 'exernalreviewfilechoose();',

                       ] ,            
                    ]) 

            
            ->add('external_reviewer_email',
                TextType::class, [
                    'attr' => ['class' => 'form-control col col-md-12 col-sm-12 col-lg-12 '],
                ])

            ->add('file_tobe_reviewed', FileType::class, [
                'label' => false,
                'mapped' => false,
                'attr' => [
                    'class' => 'form-control   col-md-12 col-sm-12 col-lg-12  ',
                    'required' => true,

                ],
                'required' => true,
            ])

            ->add('invitationDueDate', DateType::class, array(
                'placeholder' => [
                    'year' => 'Year', 'month' => 'Month', 'day' => 'Day'],
                'label' => 'Invitation response duedate',

                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
                'attr' => array(
                    'min' => (new DateTime('now'))->format('Y-m-d'),
                    'required' => true,
                    'class' => 'form-control',
                ),
            ))
            
            ->add('duedate', DateType::class, array(
                'placeholder' => [
                    'year' => 'Year', 'month' => 'Month', 'day' => 'Day'],
                'label' => 'Review duedate',
                'widget' => 'single_text',
                'format' => 'yyyy-MM-dd',
                'attr' => array(
                    'min' => (new DateTime('now'))->format('Y-m-d'),
                    'max' => $reviewAssignment->getSubmission()->getCallForProposal()->getReviewProcessEnd()->format('Y-m-d'),
                    'required' => true,
                    'class' => 'form-control',
                ),
            ))

        ;
    }

    public function configureOptions(OptionsResolver $resolver) {
        $resolver->setDefaults([
            'data_class' => ReviewAssignment::class,
        ]);
    }
}

templates/review_assignment/_delete_form.html.twig
{% if review_assignment.closed %}


	<a href="{{ path('reassign', {'id': review_assignment.id}) }}" class='btn btn-warning btn-xs '>
		Allow updating</a>

{% else %}

	<button type="button" class="btn btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">Primary
		<i class="mdi mdi-chevron-down"></i>
	</button>
	<div class="dropdown-menu" style="">
			<a href="{{ path('updatedate', {'id': review_assignment.id}) }}" class=" dropdown-item">Change date</a>

		

	<form method="post" action="{{ path('review_assignment_delete', {'id': review_assignment.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">

		<input type="hidden" name="_method" value="DELETE">
		<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ review_assignment.id) }}">
		<a href="{{ path('review_assignment_edit', {'id': review_assignment.id}) }}" class="dropdown-item">Edit</a>

		<button class="dropdown-item">
			Unassign
		</button>


	</form>

	<button type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#showDetailsModal{{review_assignment.id}}">
	Details
</button>
	</div>
{% endif %}

templates/review_assignment/_form.html.twig
{{ form_start(form) }}

{{ form_label(form.reviewer ) }}
{{ form_widget(form.reviewer ,{'attr': {'class': 'form-control'}}) }}
{{ form_label(form.invitationDueDate  ) }}
{{ form_widget(form.invitationDueDate ) }}
<label class="col-xl-12 col-lg-12  ">{{ form_label(form.duedate  ) }}</label>
<div class="form-group row">
	<br>
	<div class="col-lg-12 col-xl-12">
		<div class="input-group">
			<span class="input-group-text">
				<i class="las la-calendar"></i>
			</span>
			{{ form_widget(form.duedate  ) }}
		</div>
	</div>
</div>

<div class="form-group row">
	<div class="col-lg-12 col-xl-12">
		File to be reviewed:
		{{ form_widget(form.reviewfile ) }}
		<br>
		<div class="input-group">
			{{ form_widget(form.file_tobe_reviewed ,{'attr': {'class': 'form-control'}}) }}
			<div id="original_file" style="display:none">
				 

{% if review_assignment.submission.proposal %}
														 
																	<a href="{{ asset('/uploads/submission/'~ review_assignment.submission.proposal ) }}" class="text-primary">
																		<b>Original proposal file</b>
																		<i class="fa fa-download"></i>
																	</a>
																{% endif %}
																			</div>
		</div>
	</div>
</div>
<div class="col-lg-12 col-xl-12 offset-lg-12">
	<button type="submit" class="btn btn-outline-primary btn-sm">
		<i class="las la-save"></i>
		Assign Reviewer
	</button>
</div>
{{ form_end(form) }}

templates/review_assignment/accept_invitation.html.twig
{% extends 'base.html.twig' %}
{% block container_title %}Review Invitation
{% endblock %}
{% block title %}Review Invitation
{% endblock %}
{% block body %}
	<div class="row">
		<div class="col-lg-9">

			<div class="card">
				<div class="card-header">
					<h5>Review Invitation information<h5></div>
						<!--end card-header-->
						<div class="card-body">
							<h4 class="card-title">{{ guideline.name }}</h4>


							<p class="card-text text-muted ">{{ guideline.theGuidelline |raw}}.</p>
						</div>
						<!--end card-body-->
					</div>
					<!--end card-->
				</div>

				<div class="col-lg-3">

					<div class="card">
						<div class="card-header">
							<h5>
								Invitation info<h5></div>
								<div class="card-body ">
									<div class="ibox ">
										<div class="ibox-title">
											Title:
											{{ review_assignment.submission.title }}

											<h4 class="m-0 fw-semibold text-dark font-16 mt-3">

												Thematic area of proposal</h4>
											{{ review_assignment.submission.thematicArea }}
										</div>
										<div class="ibox-content ibox-heading">
											<br>
											<small>
												Invitation sent at:
												{{ review_assignment.invitationSentAt ? review_assignment.invitationSentAt|date('Y-m-d H:i:s') : '' }}
											</small>

											<h5 class='text-danger'>
												Duedate:
												{{ review_assignment.duedate ? review_assignment.duedate|date('Y-m-d ') : '' }}
											</h5>

										</div>

										<div class="col ">
											<form method="POST" class=' '>
												<input type="hidden" name="_token" value="{{ csrf_token('accept-invitation') }}">

												<input type="submit" class="btn btn-primary btn-lg  btn-block col-12 " name="accept-invitation" value="Accept invitation">
												<hr>
												<a href="{{ path('decline_invitation', {'id': review_assignment.id}) }}" class="btn btn-lg btn-warning btn-block col-12 ">Decline invitation</a>
											</form>

										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>

			{% endblock %}

templates/review_assignment/assigned.html.twig
{% extends 'base.html.twig' %}

{% block title %}Submission
{% endblock %}
{% block container_title %}Researches
{% endblock %}
{% block body %}
	<div class="row">
		<div class="pb-4">
			<ul class="nav-border nav nav-pills mb-0" id="pills-tab" role="tablist">
				<li class="nav-item">
					<a class="nav-link active" id="Profile_Project_tab" data-bs-toggle="pill" href="pages-profile.html#Profile_Project">Review assignments  to {{user.userInfo}} </a>
				</li> 
			</ul>
		</div>
		<div class="row">
			<div class="col-12">
				<div class="tab-content" id="pills-tabContent">
					<div class="tab-pane fade active show" id="Profile_Project" role="tabpanel" aria-labelledby="Profile_Project_tab">

						<div class="row">

							<table class="table table-bordered">
								<thead>
									<tr>
										<th>#</th>
										<th>Proposal Title</th> 
										<th>Invitation sent date</th>
										<th>Invitation  due date</th>
										<th>Review due date</th> 
										<th>Response</th> 
										<th>Action</th>
									</tr>
								</thead>
								<tbody>
									{% for myreview in myreviews %}
										<tr>
											<td>{{ loop.index }}</td>
											<td>
									<a href="{{ path('submission_show', {'id': myreview.submission.id}) }}"  >{{ myreview.submission.title }}</a>
                                            
                                            </td>

											<td>
												{% if myreview.submission.sentAt %}
													{{
                                                myreview.submission.sentAt|date() }}
												{% endif %}
											</td>
                                            	<td>
												{% if myreview.invitationDueDate %}
													{{
                                                myreview.invitationDueDate|date() }}
												{% endif %}
											</td>

										 

											<td>
												{% if myreview.dueDate %}
													{{ myreview.dueDate|date() }}
												{% endif %}
											</td>
                                            <td nowrap=nowrap>
										 
                                            
												{% if myreview.acceptedAt %}
												
                                                <span class="badge bg-success">Reviewing </span>  
											 
                                                	{% elseif myreview.rejectedAt %}
												
                                                <span class="badge bg-danger">Rejected invitation at: 	</span> {{ myreview.rejectedAt|date('d-m-y i:sa') }}
											
                                            	  
								{% elseif  myreview.Closed == 1 %}
									<span class="badge bg-warning">Review sent</span>
								{% elseif  myreview.InactiveAssignment == 1 %}
									<span class="badge bg-danger">Inactive </span>
								{% elseif  myreview.Declined == 1 %}
									<span class="badge bg-danger">Declined</span>
								{% else %}
									<span class="badge bg-warning">Pending</span>


								{% endif %}


											</td>
											<td nowrap=nowrap>



 	{% if myreview.closed %}



									<a href="{{ path('reassign', {'id': myreview.id}) }}"  class='btn btn-warning btn-xs ' > Allow updating</a>
											
											{% else %}
                    <a href="{{ path('updatedate', {'id': myreview.id}) }}" class="btn btn-purple btn-xs" >Change date</a>

							<form method="post" action="{{ path('unassign', {'id': myreview.id}) }}"
 onsubmit="return confirm('Are you sure you want to delete this item?');">

	<input type="hidden" name="_method" value="DELETE">
	<input type="hidden" name="_token" value="{{ csrf_token('delete' ~ myreview.id) }}">

	<button class="btn btn-danger btn-xs">
		Unassign
	</button>
                    


</form>
												{% endif %}

												{% if myreview.reassigned %}

									<a href="#" class="avatar-box thumb-xxs align-self-center">
										<span class="avatar-title bg-soft-danger rounded-circle font-13 font-weight-normal">
											Re
										</span>
									</a>
									

								{% endif %}

									<a href="{{ path('submission_show', {'id': myreview.submission.id}) }}"  class='btn btn-primary btn-xs ' > Details</a>
										
										
											</td>

											 
										</tr>
									{% else %}
										<tr>
											<td colspan="8">Not been  assigned to any subbmission yet!</td>
										</tr>
									{% endfor %}
								</tbody>
							</table>

						</div>

					</div>
					<!--end row-->


				</div>


			</div>
		</div>
	</div>
{% endblock %}

templates/review_assignment/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Review Assignment
{% endblock %}
{% block container_title %}Review Assignment
{% endblock %}
{% block body %}

	<div class="row">
		<div class="col-lg-6 col-md-12 col-sm-12">
			<div class="card">
				<div class="card-header">
					Edit Review Assignment
				</div>

				<div class="card-body">
					{{ form_start(editform) }}
					{{ form_widget(editform) }}

					{# <div class="modal-footer"> #}
					<button class="btn btn-soft-primary btn-lg">{{ button_label|default('Save changes') }}</button>

					{# <button type="button" class="btn btn-soft-primary btn-sm">Save changes</button> #}
					{# <button type="button" class="btn btn-soft-secondary btn-lg" data-bs-dismiss="modal">Close</button> #}


					{{ form_end(editform) }}

				</div>
			</div>
		</div>
	</div>
 {% endblock    %}

templates/review_assignment/ext_form.html.twig
{{ form_start(externalreviewerform) }}

{{ form_label(externalreviewerform.external_reviewer_name) }}
{{ form_widget(externalreviewerform.external_reviewer_name) }}
{{ form_label(externalreviewerform.middle_name) }}
{{ form_widget(externalreviewerform.middle_name) }}
{{ form_label(externalreviewerform.last_name) }}
{{ form_widget(externalreviewerform.last_name) }}
{{ form_label(externalreviewerform.external_reviewer_email) }}
{{ form_widget(externalreviewerform.external_reviewer_email) }}

{{ form_label(externalreviewerform.invitationDueDate  ) }}
{{ form_widget(externalreviewerform.invitationDueDate ) }}

<label class="col-xl-12 col-lg-12  ">
	{{ form_label(externalreviewerform.duedate  ) }}</label>


<div class="form-group row">
	<br>
	<div class="col-lg-12 col-xl-12">
		<div class="input-group">
			<span class="input-group-text">
				<i class="las la-calendar"></i>
			</span>
			{{ form_widget(externalreviewerform.duedate  ) }}


		</div>
	</div>
</div>

<div class="form-group row">
	<div class="col-lg-12 col-xl-12">
		File to be reviewed:

		<br>

		 

		{{ form_widget(externalreviewerform.reviewfile ) }}
		<br>
		<div class="input-group">
			{{ form_widget(externalreviewerform.file_tobe_reviewed ) }}
			<div id="ext_original_file" style="display:none">


				{% if review_assignment.submission.proposal %}

					<a href="{{ asset('/uploads/submission/'~ review_assignment.submission.proposal ) }}" class="text-primary">
						<b>Original proposal file</b>
						<i class="fa fa-download"></i>
					</a>
				{% endif %}
			</div>
		</div>
	</div>
</div>
<div class="col-lg-12 col-xl-12 offset-lg-12">
	<button type="submit" class="btn btn-outline-primary btn-sm">
		<i class="las la-save"></i>
		Assign external reviewer
	</button>

</div>
{{ form_end(externalreviewerform) }}


{# <script src="{{ asset('plugins/select2/select2.min.js')}}"></script> #}

 

templates/review_assignment/js.html.twig
<script type="text/javascript">


	function attachOrDoi() {
if (document.getElementById('review_assignment_reviewfile_0').checked) {
document.getElementById('original_file').style.display = 'block';
document.getElementById('review_assignment_file_tobe_reviewed').style.display = 'none';
$('#review_assignment_file_tobe_reviewed').removeAttr('required');
} else {
document.getElementById('original_file').style.display = 'none';
document.getElementById('review_assignment_file_tobe_reviewed').style.display = 'block';
}
}
{# $("#review_assignment_reviewer").select2(); #}
</script>

<script type="text/javascript">
	function exernalreviewfilechoose() {
if (document.getElementById('external_review_assignment_reviewfile_0').checked) {
document.getElementById('ext_original_file').style.display = 'block';
document.getElementById('external_review_assignment_file_tobe_reviewed').style.display = 'none';
$('#external_review_assignment_file_tobe_reviewed').removeAttr('required');
} else {

document.getElementById('ext_original_file').style.display = 'none';
document.getElementById('external_review_assignment_file_tobe_reviewed').style.display = 'block';

}
}
{# $("#review_assignment_reviewer").select2(); #}
</script>

templates/review_assignment/modal.html.twig
<div class="modal fade bd-example-modal-lg" id="exampleModalLarge" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h6 class="modal-title m-0" id="myLargeModalLabel">Choose Reviewer</h6>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
			</div>
			<!--end modal-header-->
			<div class="modal-body" id="modal-body">
			
				<div class="form-group col-12">
				 
				</div>
				<!--end row-->

			</div>
			<!--end modal-body-->
			<div class="modal-footer">
				<button type="button" class="btn btn-soft-secondary btn-sm" data-bs-dismiss="modal">Close</button>
			</div>
			<!--end modal-footer-->
		</div>
		<!--end modal-content-->
	</div>
	<!--end modal-dialog-->
</div>
<!--end modal-->