src/Entity/IRB/ApplicationType.php
<?php

namespace App\Entity\IRB;

use App\Repository\IRB\ApplicationTypeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ApplicationTypeRepository::class)
 */
class ApplicationType
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    public function __toString()
    {
       return $this->name; 
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Entity/Review.php
<?php

namespace App\Entity;

use App\Repository\ReviewRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReviewRepository::class)
 */
class Review
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $attachment;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $evaluation_attachment;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comment;

    /**
     * @ORM\ManyToOne(targetEntity=ReviewAssignment::class, inversedBy="reviews"  )
     * @ORM\JoinColumn(nullable=true)
     */
    private $reviewAssignment;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;


    /**
     * @ORM\Column(type="datetime" , nullable=true)
     */
    private $allowed_at;


    /**
     * @ORM\Column(type="string", length=255 , nullable=true)
     */
    private $remark;


    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reviews")
     */
    private $reviewed_by;

    /**
     * @ORM\ManyToOne(targetEntity=Submission::class, inversedBy="reviews")
     * @ORM\JoinColumn(nullable=false)
     */
    private $submission;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $allow_to_view;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $from_director;


    public function getId(): ?int
    {
        return $this->id;
    }
 

    public function getReviewedBy() 
    {
        return $this->reviewed_by;
    }

    public function setReviewedBy(?User $reviewed_by): self
    {
        $this->reviewed_by = $reviewed_by;

        return $this;
    }
    public function getAttachment(): ?string
    {
        return $this->attachment;
    }

    public function setAttachment(?string $attachment): self
    {
        $this->attachment = $attachment;

        return $this;
    }

    public function getEvaluationAttachment(): ?string
    {
        return $this->evaluation_attachment;
    }

    public function setEvaluationAttachment(?string $evaluation_attachment): self
    {
        $this->evaluation_attachment = $evaluation_attachment;

        return $this;
    }


    

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getReviewAssignment(): ?ReviewAssignment
    {
        return $this->reviewAssignment;
    }

    public function setReviewAssignment(?ReviewAssignment $reviewAssignment): self
    {
        $this->reviewAssignment = $reviewAssignment;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAllowedAt(): ?\DateTimeInterface
    {
        return $this->allowed_at;
    }

    public function setAllowedAt(\DateTimeInterface $allowed_at): self
    {
        $this->allowed_at = $allowed_at;

        return $this;
    }

    

    public function getRemark(): ?string
    {
        return $this->remark;
    }

    public function setRemark(string $remark): self
    {
        $this->remark = $remark;

        return $this;
    }

    public function getSubmission(): ?Submission
    {
        return $this->submission;
    }

    public function setSubmission(?Submission $submission): self
    {
        $this->submission = $submission;

        return $this;
    }

    public function getAllowToView(): ?bool
    {
        return $this->allow_to_view;
    }

    public function setAllowToView(?bool $allow_to_view): self
    {
        $this->allow_to_view = $allow_to_view;

        return $this;
    }
 
    public function getFromDirector(): ?bool
    {
        return $this->from_director;
    }

    public function setFromDirector(?bool $from_director): self
    {
        $this->from_director = $from_director;

        return $this;
    }
    

}

src/Form/RoleType.php
<?php

namespace App\Form;

use App\Utils\Constants;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RoleType extends AbstractType
{
  

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            "choices"=> [
                "System Admin" => Constants::ROLE_ADMIN,
                "President" => Constants::PRESIDENT,
                 "Vice President" => Constants::VICE_PRESIDENT,
                  "Directorate" => Constants::ROLE_DIRECTORATE,
                   "College Coordinator" => Constants::ROLE_COLLEGECOORDINATOR,
                    "Work Unit" => Constants::ROLE_WORK_UNIT,
                    "Reviewer" => Constants::ROLE_REVIEWER,
            ],
            'mapped' => false, "multiple" => true,
            "placeholder" => "Select Role"
        ]);
    }
  
    public function getParent()
    {

        return ChoiceType::class;
        
    }
}

src/Controller/IRB/ApplicationController.php
<?php

namespace App\Controller\IRB;

use App\Entity\IRB\Amendment;
use App\Entity\IRB\AmendmentAttachment;
use App\Entity\IRB\Application;
use App\Entity\IRB\ApplicationAttachment;
use App\Entity\IRB\ApplicationFeedback;
use App\Entity\IRB\ApplicationMitigationStrategy;
use App\Entity\IRB\ApplicationResearchSubject;
use App\Entity\IRB\ApplicationReview;
use App\Entity\IRB\AttachmentType;
use App\Entity\IRB\IRBReview;
use App\Entity\IRB\MitigationStrategy;
use App\Entity\IRB\MitigationStrategyGroup;
use App\Entity\IRB\RenewalRequest;
use App\Entity\IRB\ResearchSubject;
use App\Entity\IRB\ResearchSubjectCategory;
use App\Entity\IRB\ReviewStatus;
use App\Entity\IRB\ReviewStatusGroup;
use App\Entity\IRB\Revision;
use App\Entity\IRB\IrbReviewAtachement;
use App\Entity\IRB\ReviewChecklistGroup;
use App\Entity\IRB\RevisionAttachment;
use App\Entity\IrbCertificate;
use App\Form\IRB\ApplicationFilterType;
use App\Form\IRB\AmendmentType;
use App\Form\IRB\ApplicationFeedbackType;
use App\Form\IRB\ApplicationType;
use App\Form\IRB\RevisionType;
use App\Entity\IRB\IRBReviewAssignment;

use App\Repository\ApplicationFeedbackRepository;
use App\Repository\IRB\ApplicationRepository;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Dompdf\Dompdf;
use Dompdf\Options;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Address;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/irb/application')]
class ApplicationController extends AbstractController
{
    #[Route('/', name: 'application_index', methods: ['GET',"POST"])]
    public function index(ApplicationRepository $applicationRepository, Request $request, PaginatorInterface $paginatorInterface): Response
    {
         
        $this->denyAccessUnlessGranted('ROLE_BOARD_MEMBER');
        $queryBuilder = $applicationRepository->getData();
        $application_filter_form=$this->createForm(ApplicationFilterType::class)->handleRequest($request);
       
        if ($application_filter_form->isSubmitted() && $application_filter_form->isValid()) {
  
            $queryBuilder = $applicationRepository->getData($application_filter_form->getData());
 
  }
        $data= $paginatorInterface->paginate(

            $queryBuilder,
            $request->query->getInt('page', 1),
            10
        );
        return $this->render('application/index.html.twig', [
            'applications' => $data,
            'application_filter_form' => $application_filter_form->createView(),
        ]);
    }

    #[Route('/my-applications', name: 'myapplication', methods: ['GET', 'POST'])]
    public function myapplications(  Request $request, PaginatorInterface $paginatorInterface): Response
    {
        $me=$this->getUser();
        $em=$this->getDoctrine()->getManager();
        
        $allappsbyme=  array_reverse($em->getRepository(Application::class)->findBy(  array('submittedBy'=>$me)));      

        $data= $paginatorInterface->paginate( 
            $allappsbyme,
            $request->query->getInt('page', 1),
            10
        );
        return $this->render('application/my_application.html.twig', [
            'applications' => $data,
         ]); 
    }


    #[Route('/new', name: 'application_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {

        $irbReviewAtachements=  $entityManager->getRepository(IrbReviewAtachement::class)->findAll( );      

        $userdetails = $this->getUser()->getUserInfo();
        
        
        if (!$userdetails) {

            $this->addFlash("danger", "Please complete your profile first before you apply  !");

            return $this->redirectToRoute('researchworks');
        }

        if (
            $userdetails->getFirstName() == '' || $userdetails->getMidleName() == '' ||
            $userdetails->getLastName() == '' ||
            $userdetails->getCollege() == '' ||
            $userdetails->getEducationLevel() == '' || $userdetails->getAcademicRank() == ''
        ) {

            $this->addFlash("danger", "Please complete your profile first before you apply  !");

            return $this->redirectToRoute('researchworks');
        }

        
        $em=$this->getDoctrine()->getManager();
        $application = new Application();
        $application->setSubmittedBy($this->getUser());
        if($request->getMethod() !="POST"){
        foreach ($em->getRepository(ResearchSubject::class)->findBy(array(),["type"=>"ASC"]) as $key => $value) {
          
          $applicationResearch=  new ApplicationResearchSubject();
          $applicationResearch->setSubject($value);
          $application->addApplicationResearchSubject($applicationResearch);
       }
       foreach ($em->getRepository(MitigationStrategy::class)->findAll() as $key => $value) {
          
        $mitigation=  new ApplicationMitigationStrategy();
        $mitigation->setStrategy($value);
        $application->addApplicationMitigationStrategy($mitigation);
     }
     foreach ($em->getRepository(ReviewStatus::class)->findAll() as $key => $value) {
          
        $review=  new ApplicationReview();
        $review->setReview($value);
        $application->addApplicationReview($review);
     }
     foreach ($em->getRepository(AttachmentType::class)->findAll() as $key => $value) {
          
        $attachment=  new ApplicationAttachment();
        $attachment->setType($value);
        $application->addApplicationAttachment($attachment);
     }
    }
        $form = $this->createForm(ApplicationType::class, $application);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) { 


     if (!$form->get('applicationAttachments')->getdata()){
                 dd();
                 $this->addFlash("danger","attachement must be uploaded!");
                }
                 foreach ($form->get('applicationAttachments')->getdata() as $key => $value) {
          
        $attachment=  new ApplicationAttachment();
        // $attachment->setType($value);
        $application->addApplicationAttachment($attachment);
     }


 
            $application=$this->removeUnchecked($application);

            $entityManager->persist($application);
            $entityManager->flush();
            $this->addFlash("success","IRB request sent successfully");
            return $this->redirectToRoute('myapplication', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('application/new.html.twig', [
            'application' => $application,
            'irbReviewAtachements' => $irbReviewAtachements,
            'form' => $form->createView(),
            'subject_category' => $em->getRepository(ResearchSubjectCategory::class)->findAll(),
            'mitigation_strategy_group' => $em->getRepository(MitigationStrategyGroup::class)->findAll(),
            'review_status_group' => $em->getRepository(ReviewStatusGroup::class)->findAll()

        ]);
    }

    #[Route('/{id}', name: 'application_show')]
    public function show(Application $application,Request $request,EntityManagerInterface $entityManager, ApplicationFeedbackRepository $appferepo, MailerInterface $mailer): Response
    {

        if ($request->request->get('renewal')) {
                if(true){
                    $renewal=new RenewalRequest();
                    $renewal->setApplication($application);
                    $renewal->setRequestedAt(new DateTime());
                    $entityManager->persist($renewal);
                    $entityManager->flush();
                    $this->addFlash("success","Revision sent successfully");
                }else{
                    $this->addFlash("danger","You can't renew IRB clearance for this application");

                }
                return $this->redirectToRoute('application_show', ["id"=>$application->getId()], Response::HTTP_SEE_OTHER);
            }
        $amendment = new Amendment();
        $amendment->setApplication($application);
        $form = $this->createForm(AmendmentType::class, $amendment);
        $form->handleRequest($request);

        $revision = new Revision();
        $revision->setApplication($application);
        foreach ($entityManager->getRepository(AttachmentType::class)->findAll() as $key => $value) {
          
            $attachment=  new RevisionAttachment();
            $attachment->setType($value);
            $revision->addRevisionAttachments($attachment);
         }
        $form2 = $this->createForm(RevisionType::class, $revision);
        $form2->handleRequest($request);
        $review=$entityManager->getRepository(IRBReview::class)->findOneBy(['application'=>$application ]);

        if ($form->isSubmitted() && $form->isValid()) {
        $att=$request->files->get('amendment')["attachment"];
        foreach ($att as $key => $value) {
            $amendmentAtachment=new AmendmentAttachment();
            $amendmentAtachment->setUploadFile($value);
            $amendmentAtachment->setName($value->getClientOriginalName());
            $amendmentAtachment->setAmendment($amendment);
            $entityManager->persist($amendmentAtachment);
            
        }
            $entityManager->persist($amendment);
            $entityManager->flush();
            $this->addFlash("success","Amendment requested successfully");
            return $this->redirectToRoute('application_show', ["id"=>$application->getId()], Response::HTTP_SEE_OTHER);
        }

        if ($form2->isSubmitted() && $form2->isValid()) {
            foreach ($revision->getRevisionAttachments() as $k => $val) {
                if(!$val->getChecked()){
                    $revision->removeRevisionAttachments($val);
                }

templates/application/tabs/checklist.html.twig
<div class="tab-pane p-3  active" id="review-checklist" role="tabpanel">
	<div class="card">
		<div class="card-header">

			<h5>IRB application review checklist
			</h5>
		</div>
		<div class="card-body">
			<p>
				<b>INFORMATION FOR THE REVIEWER:</b>
				This is a word document, so you may download it to your computer to complete. Each of the components below must be adequately addressed within the application in order to be approved by the IRB. Please indicate whether the PI has given adequate consideration and safeguards to the following areas of concern.
				<span class="bg-warning">
					Note any concerns, recommendations or questions in the reviewer’s comment section for each component.
				</span>
			</p>
			<p>
				For expedited reviews save completed reviews as a WORD document and return to the committee chair. For a full committee review, email a copy to the chair and bring a copy to the committee meeting. The chair will summarize and compile the reviews. Copies of the reviewer checklist will be made available to applications, institutional officials, or federal officials upon request.
			</p>
			<p>

				Concerns and questions noted by reviewer(s) must be satisfactorily addressed by the applicant prior to final project approval.
			</p>


			<div>
				<form method="POST" onSubmit="return confirm('Save changes')">
                <input hidden name="review-checklist" value="true"/>
					<table class="table table-bordered table-hover">

						<tbody>

							{% for checklist_group in irb_review_checklist_group %}
								<tr>
									<th>{{toRoman(loop.index)}}.
										{{checklist_group}}</th>

									<th>YES</th>
									<th>NO</th>
									<th>NA</th>
								</tr>
								{% for checklist in checklist_group.reviewChecklists|filter(checklist =>  (checklist.answerType==1 and not checklist.parent)) %}

									{% if checklist.reviewChecklists|length >0 %}
										<tr>
											<th>
												<b style="margin-left:10px">{{toAlpha(loop.index)}}.
													{{checklist}}</b>
											</th>
											<th>YES</th>
											<th>NO</th>
											<th>NA</th>
										</tr>
										{% for child in checklist.reviewChecklists %}
											<tr>
												<th>
													<p style="margin-left:20px">{{loop.index}}.
														{{child}}</p>
												</th>
												<td><input type="radio" required name="checklist[{{child.id}}]" value="yes"></td>
												<td><input type="radio" required name="checklist[{{child.id}}]" value="yes"></td>
												<td><input type="radio" required name="checklist[{{child.id}}]" value="yes"></td>
											</tr>
										{% endfor %}
									{% else %}


										<tr>
											<td>
												<p style="margin-left:10px">{{toAlpha(loop.index)}}.
													{{checklist}}</p>
											</td>
											<td><input type="radio" required name="checklist[{{checklist.id}}]" value="yes"></td>
											<td><input type="radio" required name="checklist[{{checklist.id}}]" value="yes"></td>
											<td><input type="radio" required name="checklist[{{checklist.id}}]" value="yes"></td>
										</tr>
									{% endif %}

								{% endfor %}
								{% for checklist in checklist_group.reviewChecklists|filter(checklist =>  checklist.answerType==2) %}

									<tr>
										<td colspan="4">{{checklist}}
											<textarea name="checklist[{{checklist.id}}]" class=" form-control"></textarea>
										</td>


									</tr>
								{% endfor %}

							{% endfor %}
						</tbody>
					</table>

					<div class="mb-3 row">
						<label class="col-md-3 my-2 form-label">WAIVERS:</label>
						<p>Does the application contain a request for the committee to waive any aspects of consent or other standard IRB guidelines?

							<div class="col-md-9">
								<div class="form-check">
									<input class="form-check-input" type="radio" name="waivers" id="waivers1" value="No" checked="">
									<label class="form-check-label" for="waivers1">
										NO
									</label>
								</div>
								<div class="form-check">
									<input class="form-check-input" type="radio" name="waivers" id="waivers2" value="Yes">
									<label class="form-check-label" for="waivers2">
										YES
									</label>
								</div>
							</div>
						</p>
					</div>
					<div class="mb-3 row">
						<label class="col-md-3 my-2 form-label">RISK LEVEL:</label>
						
							<div class="col-md-9">
								<div class="form-check">
									<input class="form-check-input" type="radio" name="risk_level" id="risk_level1" value="Minimal risk" checked="">
									<label class="form-check-label" for="risk_level1">
										Minimal risk
									</label>
								</div>
								<div class="form-check">
									<input class="form-check-input" type="radio" name="risk_level" id="risk_level2" value="Greater than minimal risk">
									<label class="form-check-label" for="risk_level2">
										Greater than minimal risk
									</label>
								</div>
							</div>
						</p>
					</div>
                    	<div class="mb-3 row">
						<label class="col-md-3 my-2 form-label">RECOMMENDATION: </label>
						
							<div class="col-md-9">
								<div class="form-check">
									<input class="form-check-input" type="radio" name="recommendation" id="recommendation1" value="Table proposal (provide rationale)" checked="">
									<label class="form-check-label" for="recommendation1">
										Table proposal (provide rationale):
									</label>
								</div>
								<div class="form-check">
									<input class="form-check-input" type="radio" name="recommendation" id="recommendation1" value="Approved" checked="">
									<label class="form-check-label" for="recommendation1">
										Approve
									</label>
								</div>

								<div class="form-check">
									<input class="form-check-input" type="radio" name="recommendation" id="recommendation2" value="Disapproved">
									<label class="form-check-label" for="recommendation2">
										Disapprove
									</label>
								</div>
								<div class="form-check">
									<input class="form-check-input" type="radio" name="recommendation" id="recommendation2" value="Approve with the following stipulations/changes">
									<label class="form-check-label" for="recommendation2">
										Approve with the following stipulations/changes:
									</label>
								</div>
							</div>
						</p>
					</div>

                    	<div class="mb-3 row">
						<label class="col-md-3 my-2 form-label">HOW OFTEN THIS STUDY SHOUD BE REVIEWED: </label>
						
							<div class="col-md-9">
								
								<div class="form-check">
									<input class="form-check-input" type="radio" name="recommendation" id="recommendation1" value="option1" checked="">
									<label class="form-check-label" for="recommendation1">
										6 months
									</label>
								</div>

								<div class="form-check">
									<input class="form-check-input" type="radio" name="recommendation" id="recommendation2" value="option2">
									<label class="form-check-label" for="recommendation2">
										12 months
									</label>
								</div>
								<div class="form-check">
									<input class="form-check-input" type="radio" name="recommendation" id="recommendation2" value="option2">
									<label class="form-check-label" for="recommendation2">
                                    Other									</label>
								</div>
							</div>
						</p>
					</div>
					<button class="btn btn-primary float-end btn-block btn-lg">{{ button_label|default('Submit Review') }}</button>

				</form>
			</div>
		</div>
	</div>
</div>

templates/application/tabs/checklist_responseallowed.html.twig
<div class="tab-pane p-3  active" id="review-checklist" role="tabpanel">

	{% for re in review_assignment %}

		{% if re.allowToView ==1 and re.application.submittedBy == app.user  %}

			<div class="card m-2">
				<div class="card-header  bg-secondary">

					<h5>Reviewer #{{loop.index}}
					</h5>
				</div>
				<div class="card-body">


					<form method="POST" onsubmit="return confirm('Save changes')">
						<input hidden name="review-checklist" value="true"/>
						<table class="table table-bordered table-hover">

							<tbody>

								{% for checklist_group in irb_review_checklist_group %}
									<tr>
										<th>{{toRoman(loop.index)}}.
											{{checklist_group}}</th>

										<th>Response</th>
									</tr>
									{% set parents = {} %}
									{% for checklist in re.reviewerResponses|filter(  checklist =>  (checklist.checklist.answerType==1 and  checklist.checklist.checklistGroup ==  checklist_group) ) %}

										{% if checklist.checklist.parent %}
											{% set parents = parents|merge({("key" ~ checklist.checklist.parent.id):checklist.checklist.parent}) %}

										{% else %}


											<tr>
												<td>
													<p style="margin-left:10px">{{toAlpha(loop.index)}}.
														{{checklist}}</p>
												</td>
												<td>{{ checklist.answer }}</td>
											</tr>
										{% endif %}

									{% endfor %}
									{% for checklist_parent in parents %}
										<tr>
											<th>
												<b style="margin-left:10px">{{toRoman(loop.index)}}.
													{{checklist_parent}}<b></th>

													<th>Response</th>
												</tr>
												{% for checklist in re.reviewerResponses|filter(checklist =>  (checklist.checklist.answerType==1 and  checklist.checklist.parent ==  checklist_parent)) %}


													<tr>
														<td>
															<p style="margin-left:20px">{{loop.index}}.
																{{checklist}}</p>
														</td>
														<td>{{ checklist.answer }}</td>
													</tr>

												{% endfor %}
											{% endfor %}


										{% endfor %}
									</tbody>
								</table>

								<div class="mb-3 row">
									<label class="col-md-3 my-2 form-label">WAIVERS:</label>
									<p>Does the application contain a request for the committee to waive any aspects of consent or other standard IRB guidelines?

										<div class="col-md-9">
											<u>
												{{  re.waiver}}</u>
										</div>
									</p>

								</div>
								<div class="mb-3 row">
									<label class="col-md-3 my-2 form-label">RISK LEVEL:</label>
									<u>{{  re.riskLevel}}</u>


								</div>
								<div class="mb-3 row">
									<label class="col-md-3 my-2 form-label">RECOMMENDATION:
									</label>

									<u>
										{{  re.recommendation}}</u>

								</div>

								<div class="mb-3 row">
									<label class="col-md-3 my-2 form-label">HOW OFTEN THIS STUDY SHOUD BE REVIEWED:
									</label>
									<u>
										{{  re.howOftenStudyReviewed}}</u>
								</div>
							</tbody>
						</tbody>
					</form>
				</div>
			</div>
		{% else %}

			{% if is_granted("ROLE_VICE_CHAIR") or is_granted("ROLE_CHAIR")   or is_granted("ROLE_SECRETARY")   %}

				<div class="card m-2">
					<div class="card-header  bg-secondary">

						<h5>Reviewer #{{loop.index}} {{re.irbreviewer}}
						</h5>
					</div>
					<div class="card-body">


						<form method="POST" onsubmit="return confirm('Save changes')">
							<input hidden name="review-checklist" value="true"/>
							<table class="table table-bordered table-hover">

								<tbody>

									{% for checklist_group in irb_review_checklist_group %}
										<tr>
											<th>{{toRoman(loop.index)}}.
												{{checklist_group}}</th>

											<th>Response</th>
										</tr>
										{% set parents = {} %}
										{% for checklist in re.reviewerResponses|filter(  checklist =>  (checklist.checklist.answerType==1 and  checklist.checklist.checklistGroup ==  checklist_group) ) %}

											{% if checklist.checklist.parent %}
												{% set parents = parents|merge({("key" ~ checklist.checklist.parent.id):checklist.checklist.parent}) %}

											{% else %}


												<tr>
													<td>
														<p style="margin-left:10px">{{toAlpha(loop.index)}}.
															{{checklist}}</p>
													</td>
													<td>{{ checklist.answer }}</td>
												</tr>
											{% endif %}

										{% endfor %}
										{% for checklist_parent in parents %}
											<tr>
												<th>
													<b style="margin-left:10px">{{toRoman(loop.index)}}.
														{{checklist_parent}}<b></th>

														<th>Response</th>
													</tr>
													{% for checklist in re.reviewerResponses|filter(checklist =>  (checklist.checklist.answerType==1 and  checklist.checklist.parent ==  checklist_parent)) %}


														<tr>
															<td>
																<p style="margin-left:20px">{{loop.index}}.
																	{{checklist}}</p>
															</td>
															<td>{{ checklist.answer }}</td>
														</tr>

													{% endfor %}
												{% endfor %}


											{% endfor %}
										</tbody>
									</table>

									<div class="mb-3 row">
										<label class="col-md-3 my-2 form-label">WAIVERS:</label>
										<p>Does the application contain a request for the committee to waive any aspects of consent or other standard IRB guidelines?

											<div class="col-md-9">
												<u>
													{{  re.waiver}}</u>
											</div>
										</p>

									</div>
									<div class="mb-3 row">
										<label class="col-md-3 my-2 form-label">RISK LEVEL:</label>
										<u>{{  re.riskLevel}}</u>


									</div>
									<div class="mb-3 row">
										<label class="col-md-3 my-2 form-label">RECOMMENDATION:
										</label>

										<u>
											{{  re.recommendation}}</u>

									</div>

									<div class="mb-3 row">
										<label class="col-md-3 my-2 form-label">HOW OFTEN THIS STUDY SHOUD BE REVIEWED:
										</label>
										<u>
											{{  re.howOftenStudyReviewed}}</u>
									</div>
								</tbody>
							</tbody>
						</form>
					</div>

					{% if re.allowToView %}
						<form>
							<button type="button" class='btn m-4 btn-soft-success btn-lg'>
								Comments sent</button>
						</form>
					{% else %}
						<form method="post" action="{{ path('send_comment', {'id': re.id}) }}" onsubmit="return confirm('Are you sure you want to send review comments to PI ?');">
							<input type="hidden" name="_token" value="{{ csrf_token('send' ~ re.id) }}">
							<button class="btn btn-soft-primary btn-lg m-4 ">
								Send comments to applicant</button>
						</form>
					{% endif %}
				</div>
			{% endif %}
		{% endif %}
	{% endfor %}
</div>