src/Entity/WorkUnit.php
<?php

namespace App\Entity;

use App\Repository\WorkUnitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=WorkUnitRepository::class)
 */
class WorkUnit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="text",   nullable=true)
     */
    private $principal_contact;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $identification_code;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $mission;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $objective;

    /**
     * @ORM\OneToMany(targetEntity=Submission::class, mappedBy="workunit")
     */
    private $submissions;

    /**
     * @ORM\OneToMany(targetEntity=Guidelines::class, mappedBy="work_unit")
     */
    private $guidelines;

 
    /**
     * @ORM\OneToMany(targetEntity=ThematicArea::class, mappedBy="work_unit")
     */
    private $thematicAreas;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $prefix;
 
   

    /**
     * @ORM\OneToMany(targetEntity=GuidelineForReviewer::class, mappedBy="workunit")
     */
    private $guidelineForReviewers;

    public function __construct()
    {
        $this->submissions = new ArrayCollection();
        $this->guidelines = new ArrayCollection();
        $this->callForProposals = new ArrayCollection();
        $this->thematicAreas = new ArrayCollection();
         $this->guidelineForReviewers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

   public function __toString(): string
    {
        return $this->name;
    }


    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrincipalContact(): ?string
    {
        return $this->principal_contact;
    }

    public function setPrincipalContact(?string $principal_contact): self
    {
        $this->principal_contact = $principal_contact;

        return $this;
    }

    public function getIdentificationCode(): ?string
    {
        return $this->identification_code;
    }

    public function setIdentificationCode(?string $identification_code): self
    {
        $this->identification_code = $identification_code;

        return $this;
    }

    public function getMission(): ?string
    {
        return $this->mission;
    }

    public function setMission(?string $mission): self
    {
        $this->mission = $mission;

        return $this;
    }

    public function getObjective(): ?string
    {
        return $this->objective;
    }

    public function setObjective(?string $objective): self
    {
        $this->objective = $objective;

        return $this;
    }

    /**
     * @return Collection|Submission[]
     */
    public function getSubmissions(): Collection
    {
        return $this->submissions;
    }

    public function addSubmission(Submission $submission): self
    {
        if (!$this->submissions->contains($submission)) {
            $this->submissions[] = $submission;
            $submission->setWorkunit($this);
        }

        return $this;
    }

    public function removeSubmission(Submission $submission): self
    {
        if ($this->submissions->removeElement($submission)) {
            // set the owning side to null (unless already changed)
            if ($submission->getWorkunit() === $this) {
                $submission->setWorkunit(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Guidelines[]
     */
    public function getGuidelines(): Collection
    {
        return $this->guidelines;
    }

    public function addGuideline(Guidelines $guideline): self
    {
        if (!$this->guidelines->contains($guideline)) {
            $this->guidelines[] = $guideline;
            $guideline->setWorkUnit($this);
        }

        return $this;
    }

    public function removeGuideline(Guidelines $guideline): self
    {
        if ($this->guidelines->removeElement($guideline)) {
            // set the owning side to null (unless already changed)
            if ($guideline->getWorkUnit() === $this) {
                $guideline->setWorkUnit(null);
            }
        }

        return $this;
    }

    
    /**
     * @return Collection|ThematicArea[]
     */
    public function getThematicAreas(): Collection
    {
        return $this->thematicAreas;
    }

    public function addThematicArea(ThematicArea $thematicArea): self
    {
        if (!$this->thematicAreas->contains($thematicArea)) {
            $this->thematicAreas[] = $thematicArea;
            $thematicArea->setWorkUnit($this);
        }

        return $this;
    }

    public function removeThematicArea(ThematicArea $thematicArea): self
    {
        if ($this->thematicAreas->removeElement($thematicArea)) {
            // set the owning side to null (unless already changed)
            if ($thematicArea->getWorkUnit() === $this) {
                $thematicArea->setWorkUnit(null);
            }
        }

        return $this;
    }

    public function getPrefix(): ?string
    {
        return $this->prefix;
    }

    public function setPrefix(?string $prefix): self
    {
        $this->prefix = $prefix;

        return $this;
    }
 

    /**
     * @return Collection|GuidelineForReviewer[]
     */
    public function getGuidelineForReviewers(): Collection
    {
        return $this->guidelineForReviewers;
    }

    public function addGuidelineForReviewer(GuidelineForReviewer $guidelineForReviewer): self
    {
        if (!$this->guidelineForReviewers->contains($guidelineForReviewer)) {
            $this->guidelineForReviewers[] = $guidelineForReviewer;
            $guidelineForReviewer->setWorkunit($this);
        }

        return $this;
    }

    public function removeGuidelineForReviewer(GuidelineForReviewer $guidelineForReviewer): self
    {
        if ($this->guidelineForReviewers->removeElement($guidelineForReviewer)) {
            // set the owning side to null (unless already changed)
            if ($guidelineForReviewer->getWorkunit() === $this) {
                $guidelineForReviewer->setWorkunit(null);
            }
        }

        return $this;
    }
}

src/Form/WorkUnitType.php
<?php

namespace App\Form;

use App\Entity\WorkUnit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use FOS\CKEditorBundle\Form\Type\CKEditorType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
class WorkUnitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description',   CKEditorType::class,[
    'attr'=>['placeholder'=>'Describe your reason why',

    'class' => 'form-control',
       
                 'required' => false,
            
],])     
            ->add('principal_contact' ,  CKEditorType::class,[
    'attr'=>['placeholder'=>'Describe your reason why',

    'class' => 'form-control',
       
                 'required' => false,
            
],])     

            ->add('identification_code')
             
 ->add('mission',     CKEditorType::class,[
    'attr'=>['placeholder'=>'Describe your reason why',

    'class' => 'form-control',
       
                 'required' => false,
            
],])     
                        ->add('prefix')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => WorkUnit::class,
        ]);
    }
}

src/Controller/WorkUnitController.php
<?php

namespace App\Controller;

use App\Entity\GuidelineForReviewer;
use App\Entity\Guidelines;
use App\Entity\ThematicArea;
use App\Entity\WorkUnit;
use App\Form\GuidelineForReviewerType;
use App\Form\ThematicAreaType;
use App\Form\WorkUnitType;
use App\Repository\GuidelinesRepository;
use App\Repository\ThematicAreaRepository;
use App\Repository\WorkUnitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/colleges")
 */
class WorkUnitController extends AbstractController {
    /**
     * @Route("/", name="work_unit_index", methods={"GET"})
     */
    public function index(WorkUnitRepository $workUnitRepository): Response {
        return $this->render('work_unit/index.html.twig', [
            'work_units' => $workUnitRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="work_unit_new", methods={"GET","POST"})
     */
    public function new (Request $request): Response {
        $workUnit = new WorkUnit();
        $form = $this->createForm(WorkUnitType::class, $workUnit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($workUnit);
            $entityManager->flush();

            return $this->redirectToRoute('work_unit_index');
        }

        return $this->render('work_unit/new.html.twig', [
            'work_unit' => $workUnit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{prefix}/view", name="work_unit_show", methods={"GET","POST"})
     */
    public function show(Request $request, WorkUnit $workUnit, ThematicAreaRepository $thematicAreaRepository, GuidelinesRepository $guidelinesRepository): Response {

        $entityManager = $this->getDoctrine()->getManager();
        $thematicAreas = $entityManager->getRepository(ThematicArea::class)->findBy(['work_unit' => $workUnit]);
        $guidelines = $entityManager->getRepository(Guidelines::class)->findBy(['work_unit' => $workUnit]);
        $thematicArea = new ThematicArea();
        $thematicAreaform = $this->createForm(ThematicAreaType::class, $thematicArea);
        $thematicAreaform->handleRequest($request);
        if ($thematicAreaform->isSubmitted() && $thematicAreaform->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $thematicArea->setWorkunit($workUnit);
            # $thematicArea->setCreatedAt(new \DateTime());
            $entityManager->persist($thematicArea);
            $entityManager->flush();

            return $this->redirectToRoute('work_unit_show', array('prefix' => $workUnit->getPrefix()));
        }

        $guideline_for_reviewers = $entityManager->getRepository(GuidelineForReviewer::class)->findBy(['workunit' => $workUnit]);
        $guidelineForReviewer = new GuidelineForReviewer();
        $formGuidelineForReviewer = $this->createForm(GuidelineForReviewerType::class, $guidelineForReviewer);
        $formGuidelineForReviewer->handleRequest($request);

        if ($formGuidelineForReviewer->isSubmitted() && $formGuidelineForReviewer->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $guidelineForReviewer->setWorkunit($workUnit);
            $guidelineForReviewer->setCreatedAt(new \DateTime());
            $entityManager->persist($guidelineForReviewer);
            $entityManager->flush();
            return $this->redirectToRoute('work_unit_show', array('prefix' => $workUnit->getPrefix()));
        }
        $guideline = new Guidelines();
        $guidelineform = $this->createFormBuilder($guideline)
            ->add('guideline')

            ->add('attachment', FileType::class, [
                'label' => 'Guideline attachment  file',

                'mapped' => false,
                'required' => false,

            ])
            ->getForm();
        $guidelineform->handleRequest($request);

        if ($guidelineform->isSubmitted() && $guidelineform->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $file3 = $guideline->getAttachment();
            if ($file3) {
                echo ' file not uploaded';
            } else {
                $file3 = $guidelineform->get('attachment')->getData();
                $fileName3 = md5(uniqid()) . '.' . $file3->guessExtension();
                $file3->move($this->getParameter('review_files'), $fileName3);
                $guideline->setWorkunit($workUnit);
                $guideline->setCreatedAt(new \DateTime());
                $guideline->setAttachment($fileName3);
            }

            if ($guidelineform->isSubmitted() && $guidelineform->isValid()) {
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($guideline);
                $entityManager->flush();

                return $this->redirectToRoute('work_unit_show', array('prefix' => $workUnit->getPrefix()));
            }
        }

        //to be changerd later
        $form = $this->createForm(WorkUnitType::class, $workUnit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('work_unit_show', array('prefix' => $workUnit->getPrefix()));
        }
        return $this->render('work_unit/show.html.twig', [
            'work_unit' => $workUnit,
            'guidelines' => $guidelines,
            'guideline_for_reviewers' => $guideline_for_reviewers,
            'formguidelineforReviewer' => $formGuidelineForReviewer->createView(),
            'form' => $form->createView(),
            'guidelineform' => $guidelineform->createView(),
            'thematicAreaform' => $thematicAreaform->createView(),
            'thematic_areas' => $thematicAreas,
        ]);
    }

/**
 * @Route("/{prefix}/details", name="work_unit_details", methods={"GET","POST"})
 */
    public function details(Request $request, WorkUnit $workUnit, ThematicAreaRepository $thematicAreaRepository, GuidelinesRepository $guidelinesRepository): Response {

        $entityManager = $this->getDoctrine()->getManager();
        $thematicAreas = $entityManager->getRepository(ThematicArea::class)->findBy(['work_unit' => $workUnit]);
        $guidelines = $entityManager->getRepository(Guidelines::class)->findBy(['work_unit' => $workUnit]);

        return $this->render('work_unit/details.html.twig', [
            'work_unit' => $workUnit,
            'guidelines' => $guidelines,
            'thematic_areas' => $thematicAreas,
        ]);
    }

    /**
     * @Route("{id}/download", name="download", methods={"GET","POST"})
     */
    public function download(Guideline $guideline, WorkUnit $workUnit) {
        $entityManager = $this->getDoctrine()->getManager();
        $guidelines = $entityManager->getRepository(Guidelines::class)->findBy(['work_unit' => $workUnit]);
        // send the file contents and force the browser to download it
        $theattachment = $guidelines->getAttachment();
        return $this->file('/proposal/$theattachment');
    }
    /**
     * @Route("/{id}/edit", name="work_unit_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, WorkUnit $workUnit): Response {
        $form = $this->createForm(WorkUnitType::class, $workUnit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('work_unit_index');
        }

        return $this->render('work_unit/edit.html.twig', [
            'work_unit' => $workUnit,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="work_unit_delete", methods={"DELETE"})
     */
    public function delete(Request $request, WorkUnit $workUnit): Response {
        if ($this->isCsrfTokenValid('delete' . $workUnit->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($workUnit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('work_unit_index');
    }
}

templates/work_unit/_delete_form.html.twig
<form method="post" action="{{ path('work_unit_delete', {'id': work_unit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ work_unit.id) }}">
    <button class="btn">Delete</button>
</form>

templates/work_unit/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/work_unit/details.html.twig
{% extends 'homepage.html.twig' %}

{% block title %}Submission{% endblock %}
  {% block container_title %}College{% endblock %} 
{% block body %}
  
     <ul class='table table-striped'>
        {% for thematic_area in thematic_areas %}
          
                <li class='table table-stripe'>{{ loop.index }}.  
                 {{ thematic_area.name }} 
                 {{ thematic_area.description }}</li>
                
            
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
       </ul>
 <hr> 
 
 <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Guideline</th>
                
            </tr>
        </thead>
        <tbody>
        {% for guideline in guidelines %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ guideline.guideline }}</td>
                 
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table> 

                          
{% endblock %}

templates/work_unit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Work Unit index{% endblock %}
 {% block container_title %}Work units{% endblock %} 
{% block body %} 
    <table  class="table  table-striped" >
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th> 
                <th>Prefix</th> 
                <th>Identification code</th> 
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for work_unit in work_units %}
            <tr>
                <td>{{ loop.index  }}</td>
                <td>{{ work_unit.name }}</td>
                <td>{{ work_unit.prefix }}</td> 
                <td>{{ work_unit.identificationCode }}</td> 
                <td> 
                    <a href="{{ path('work_unit_show', {'prefix': work_unit.prefix}) }}" class='btn  btn-info btn-xs'>Details</a>
                    <a href="{{ path('work_unit_edit', {'id': work_unit.id}) }}" class='btn btn-warning btn-xs'> Edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('work_unit_new') }}">Create new</a>
{% endblock %}

templates/work_unit/show.html (copy).twig
{% extends 'base.html.twig' %}

{% block title %}WorkUnit{% endblock %}

{% block body %}
    <h1>WorkUnit</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ work_unit.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ work_unit.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ work_unit.description }}</td>
            </tr>
            <tr>
                <th>Principal_contact</th>
                <td>{{ work_unit.principalContact }}</td>
            </tr>
            <tr>
                <th>Identification_code</th>
                <td>{{ work_unit.identificationCode }}</td>
            </tr>
            <tr>
                <th>Mission</th>
                <td>{{ work_unit.mission }}</td>
            </tr>
            <tr>
                <th>Objective</th>
                <td>{{ work_unit.objective }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('work_unit_index') }}">back to list</a>

    <a href="{{ path('work_unit_edit', {'id': work_unit.id}) }}">edit</a>

    {{ include('work_unit/_delete_form.html.twig') }}
{% endblock %}

templates/work_unit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Submission{% endblock %}
  {% block container_title %}Work unit directorate office: {{ work_unit.name}}{% endblock %} 
{% block body %}
<div class="row">
            <div class="col-lg-9">
                
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">College</h4>
                                    <p class="text-muted mb-0"> details</p>
                                </div><!--end card-header-->
                                <div class="card-body">
                                    <!-- Nav tabs -->
                                    <ul class="nav nav-pills nav-justified" role="tablist">
                                        <li class="nav-item waves-effect waves-light">
                                            <a class="nav-link active" data-bs-toggle="tab" href="tab#home-1" role="tab" aria-selected="false">Details</a>
                                        </li>
                                        <li class="nav-item waves-effect waves-light">
                                            <a class="nav-link" data-bs-toggle="tab" href="tab#profile-1" role="tab" aria-selected="false">Themaice areas</a>
                                        </li>
                                        <li class="nav-item waves-effect waves-light">
                                            <a class="nav-link  " data-bs-toggle="tab" href="tab#settings-1" role="tab" aria-selected="true">Guidelines</a>
                                        </li>
                                        <li class="nav-item waves-effect waves-light">
                                            <a class="nav-link  " data-bs-toggle="tab" href="tab#manage-1" role="tab" aria-selected="true">Edit</a>
                                        </li>
                                    </ul>
    
                                    <!-- Tab panes -->
                                    <div class="tab-content">
                                        <div class="tab-pane active p-3" id="home-1" role="tabpanel">
                                           <div class="table-responsive">
                                <table class="table shoping-cart-table">

                                    <tbody>
                                    <tr>  
                                        <td class="desc">
                                            <h3>
                                            <a href="#" class="text-navy">
 {{ work_unit.name }}
                                            </a>
                                            </h3>
                                            <p class="medium">
                                             {{ work_unit.description |raw}}
                                            </p> 
                                               <p class="medium">
            <h4 class='text:success'> Principal Contact:</h4>
                                                {{ work_unit.PrincipalContact |raw }}
                                                        <h4 class='text:success'> Description:</h4>
                                              {{ work_unit.description |raw}}
                                            </p> 
                                           <h4 class='text-success'> Identification  Code</h4>                                            
                                            {{ work_unit.identificationCode }}
                                            <p>
                                          <h4 class='text-success'> Objective</h4>
                                           {{ work_unit.Objective }}
                                        
                                          <h4 class='text-success'> Institutional Reviewers Board </h4>
    
<div class='profiles'>
    <table class='table table-striped text-left'>
        <thead>
            <tr>
                <th>#</th>
                <th>Specialization</th>
                <th>Affiliation</th>
 
            </tr>
        </thead>
        <tbody>
        {% for institutional_reviewers_board in institutional_reviewers_boards %}
            <tr style="text-align:left">
                <td>{{ institutional_reviewers_board.id }}</td>
                <td  style="text-align:left">{{ institutional_reviewers_board.specialization }}</td>
                <td style="text-align:left" nowrap=nowrap>{{ institutional_reviewers_board.affiliation }}</td>
               
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
 </div>
                                                  
                                          <h4 class='text-success'> Mission</h4>
                                           {{ work_unit.mission|raw }}
                                            <div class="m-t-sm">
                                                <a href="#" class="text-muted">Created at</a> 
                                            </div>
                                        </td> 
                                    </tr>
                                    </tbody>
                                </table>
                            </div>  
                                            <p class="text-muted mb-0">
                                                Raw denim you probably haven't heard of them jean shorts Austin.
                                            </p>
                                        </div>
                                        <div class="tab-pane p-3" id="profile-1" role="tabpanel">
                                               <table class="table table-striped"> 
<thead>
            <tr>
                <th>#</th>
                <th>Name</th>
 
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for thematic_area in thematic_areas %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ thematic_area.name }}</td>
 
                <td nowrap=nowrap>
                    <a href="{{ path('thematic_area_show', {'id': thematic_area.id}) }}">show</a>
                    <a href="{{ path('thematic_area_edit', {'id': thematic_area.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
          </tbody>
    </table>
 <hr>
<h3 class='text-success'>New Thematic area</h3>
 {{ form_start(thematicAreaform) }}
    {{ form_widget(thematicAreaform) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(thematicAreaform) }}
                                        </div>
                                        <div class="tab-pane p-3  " id="settings-1" role="tabpanel">
                                                <h4 class='text-success'> Guideline For Authors   </h4>

 <table class="table table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Guideline body</th>
 
 
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for guideline in guidelines %}
            <tr>
                <td>{{ guideline.id }}</td>
                <td>{{ guideline.guideline }}</td>
               <td>
                    <a href="{{ path('guidelines_show', {'id': guideline.id}) }}">show</a>
                    <a href="{{ path('guidelines_edit', {'id': guideline.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
                                              <h4 class='text-success'> New Guideline For Authors   </h4>
 {{ form_start(guidelineform) }}
    {{ form_widget(guidelineform) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(guidelineform) }}

                                          <h4 class='text-success'> Guideline For reviewers   </h4>
                                          <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>The guidellines body </th>
                 
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for guideline_for_reviewer in guideline_for_reviewers %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ guideline_for_reviewer.name }}</td>
                <td>{{ guideline_for_reviewer.theGuidelline }}</td>
 
                <td>
                    <a href="{{ path('guideline_for_reviewer_show', {'id': guideline_for_reviewer.id}) }}">show</a>
                    <a href="{{ path('guideline_for_reviewer_edit', {'id': guideline_for_reviewer.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
                                          <h4 class='text-success'>New  Guideline For reviewers   </h4>
{{ form_start(formguidelineforReviewer) }}
    {{ form_widget(formguidelineforReviewer) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(formguidelineforReviewer) }}
                              
                                        </div>
                                        <div class="tab-pane p-3  " id="manage-1" role="tabpanel">
                                             
    {{ include('work_unit/_form.html.twig', {'button_label': 'Update'}) }}


    {{ include('work_unit/_delete_form.html.twig') }}
                                        </div>
                                    </div>    
                                </div><!--end card-body-->
                            </div><!--end card-->
                        </div>
 
  
            <div class="col-lg-3">
                <div class="wrapper wrapper-content project-manager">
                    <h4>Guidelines</h4>
 
                   
                    <h5>IRBs</h5>
                    <ul class="list-unstyled project-files">
                         
 dd
                    </ul>
                    
                </div>
            </div>
        </div> 
{% endblock %}